swagger: '2.0'
x-api-store-tags:
  - goods
  - services
x-api-store-plans:
  public:
    name: Public Plan
    description: All other users should subscribe to the Public Plan.
  internal:
    name: Internal Plan
    description: The Internal Plan is for internal government use only.
info:
  title: Canadian Nutrient File (CNF)
  description: The Canadian Nutrient File (CNF) is the standard reference food composition database reporting the amount of nutrients in foods commonly consumed in Canada.
  version: '0.1'

schemes:
  - https
host: cnf-hc-sc-apicast-staging.dev.api.canada.ca
basePath: /api/canadian-nutrient-file
produces:
  - application/json
  - application/xml

paths:
  /food:
    get:
      tags:
        - Food
      description: Returns all foods.
      parameters:
        - $ref: '#/parameters/UserKeys'
        - $ref: '#/parameters/QueryLang'
        - $ref: '#/parameters/QueryType'
      responses:
        '200':
          description: Returns a list of all foods, or if an ID is provided, the list of all foods that correspond to the given food code
          schema:
            type: array
            items:
              $ref: '#/definitions/Food'
            xml:
              name: Foods
              wrapped: true
        '204':
          $ref: '#/definitions/204'
        '404':
          $ref: '#/definitions/404'

  /food/{id}:
    get:
      tags:
        - Food
      description: Returns all foods.
      parameters:
        - $ref: '#/parameters/UserKeys'
        - $ref: '#/parameters/QueryLang'
        - $ref: '#/parameters/QueryType'
        - name: id
          in: path
          required: true
          type: string
          description: Limit results to those with matching food code
      responses:
        '200':
          description: Returns a list of all foods, or if an ID is provided, the list of all foods that correspond to the given food code
          schema:
            type: array
            items:
              $ref: '#/definitions/Food'
            xml:
              name: Foods
              wrapped: true
        '204':
          $ref: '#/definitions/204'
        '404':
          $ref: '#/definitions/404'

  /nutrientname:
    get:
      tags:
        - Nutrient
      description: Returns all nutrient names.
      parameters:
        - $ref: '#/parameters/UserKeys'
        - $ref: '#/parameters/QueryLang'
        - $ref: '#/parameters/QueryType'
        - name: id
          in: query
          type: string
          description: Limit results to those with matching nutrient name identification number
      responses:
        '200':
          description: Returns a list of all nutrient names, or if an ID is provided, the list of all nutrient names that correspond to the given nutrient name identification number
          schema:
            type: array
            items:
              $ref: '#/definitions/NutrientName'
            xml:
              name: NutrientNames
              wrapped: true
        '204':
          $ref: '#/definitions/204'
        '404':
          $ref: '#/definitions/404'

  /nutrientgroup:
    get:
      tags:
        - Nutrient
      description: Returns all nutrient groups.
      parameters:
        - $ref: '#/parameters/UserKeys'
        - $ref: '#/parameters/QueryLang'
        - $ref: '#/parameters/QueryType'
        - name: id
          in: query
          type: string
          description: Limit results to those with matching nutrient group identification number
      responses:
        '200':
          description: Returns a list of all nutrient groups, or if an ID is provided, the list of all nutrient groups that correspond to the given nutrient group identification number
          schema:
            type: array
            items:
              $ref: '#/definitions/NutrientGroup'
            xml:
              name: NutrientGroups
              wrapped: true
        '204':
          $ref: '#/definitions/204'
        '404':
          $ref: '#/definitions/404'

  /nutrientsource:
    get:
      tags:
        - Nutrient
      description: Returns all nutrient sources.
      parameters:
        - $ref: '#/parameters/UserKeys'
        - $ref: '#/parameters/QueryLang'
        - $ref: '#/parameters/QueryType'
        - name: id
          in: query
          type: string
          description: Limit results to those with matching nutrient source identification number
      responses:
        '200':
          description: Returns a list of all nutrient sources, or if an ID is provided, the list of all nutrient sources that correspond to the given nutrient source identification number
          schema:
            type: array
            items:
              $ref: '#/definitions/NutrientSource'
            xml:
              name: NutrientSources
              wrapped: true
        '204':
          $ref: '#/definitions/204'
        '404':
          $ref: '#/definitions/404'

  /nutrientamount:
    get:
      tags:
        - Nutrient
      description: Returns all nutrient amounts.
      parameters:
        - $ref: '#/parameters/UserKeys'
        - $ref: '#/parameters/QueryLang'
        - $ref: '#/parameters/QueryType'
        - name: id
          in: query
          type: string
          description: Limit results to those with matching food code
      responses:
        '200':
          description: Returns a list of all nutrient amounts, or if an ID is provided, the list of all nutrient amounts that correspond to the given food code
          schema:
            type: array
            items:
              $ref: '#/definitions/NutrientAmount'
            xml:
              name: NutrientAmounts
              wrapped: true
        '204':
          $ref: '#/definitions/204'
        '404':
          $ref: '#/definitions/404'

  /servingsize:
    get:
      tags:
        - Serving Size
      description: Returns all measures and conversion factors.
      parameters:
        - $ref: '#/parameters/UserKeys'
        - $ref: '#/parameters/QueryLang'
        - $ref: '#/parameters/QueryType'
        - name: id
          in: query
          type: string
          description: Limit results to those with matching food code
      responses:
        '200':
          description: Returns a list of all serving sizes, or if an ID is provided, the list of all serving sizes that correspond to the given food code
          schema:
            type: array
            items:
              $ref: '#/definitions/ServingSize'
            xml:
              name: ServiceSizes
              wrapped: true
        '204':
          $ref: '#/definitions/204'
        '404':
          $ref: '#/definitions/404'

  /refuseamount:
    get:
      tags:
        - Serving Size
      description: Returns all refuse amounts.
      parameters:
        - $ref: '#/parameters/UserKeys'
        - $ref: '#/parameters/QueryLang'
        - $ref: '#/parameters/QueryType'
        - name: id
          in: query
          type: string
          description: Limit results to those with matching food code
      responses:
        '200':
          description: Returns a list of all refuse amounts, or if an ID is provided, the list of all refuse amounts that correspond to the given food code
          schema:
            type: array
            items:
              $ref: '#/definitions/RefuseAmount'
            xml:
              name: RefuseAmounts
              wrapped: true
        '204':
          $ref: '#/definitions/204'
        '404':
          $ref: '#/definitions/404'

  /yieldamount:
    get:
      tags:
        - Yield Amount
      description: Returns all yield amounts.
      parameters:
        - $ref: '#/parameters/UserKeys'
        - $ref: '#/parameters/QueryLang'
        - $ref: '#/parameters/QueryType'
        - name: id
          in: query
          type: string
          description: Limit results to those with matching food code
      responses:
        '200':
          description: Returns a list of all yield amounts, or if an ID is provided, the list of all yield amounts that correspond to the given food code
          schema:
            type: array
            items:
              $ref: '#/definitions/YieldAmount'
            xml:
              name: YieldAmounts
              wrapped: true
        '204':
          $ref: '#/definitions/204'
        '404':
          $ref: '#/definitions/404'

definitions:
  '204':
    type: string
  '404':
    type: string

  Food:
    type: object
    description: It contains a description and the code of each food. A food cannot be further decomposed into ingredients.
    properties:
      food_code:
        type: string
        description: The code assigned to a food.
      food_description:
        type: string
        description: The complete food name.
    xml:
      name: Food

  NutrientName:
    type: object
    description: It contains a list of different nutrients.
    properties:
      nutrient_name_id:
        type: string
        description: The identification number assigned to a nutrient.
      nutrient_code:
        type: string
        description: The code assigned to a nutrient.
      nutrient_symbol:
        type: string
        description: The nutrient symbol or abbreviation of the nutrients. They may differ from international nomenclature.
      unit:
        type: string
        description: The unit of measure (e.g., mg, g, mcg).
      nutrient_name:
        type: string
        description: The name of the nutrient.
      tagname:
        type: string
        description: A unique Abbreviation for a food component developed by International Network of Food Data Systems (INFOODS) to aid in the interchange of data.
      nutrient_decimals:
        type: string
        description: The number of decimal places used in the rounding of the nutrient value.
      nutrient_web_order:
        type: string
        description: The order to display the nutrient.
      nutrient_web_name:
        type: string
        description: The name of the nutrient for the WEB.
      nutrient_group_id:
        type: string
        description: The identification number of the nutrient group.
    xml:
      name: NutrientName

  NutrientGroup:
    type: object
    description: It contains a list of different nutrient group headings based on similar characteristics of the nutrients.
    properties:
      nutrient_group_id:
        type: string
        description: The identification number assigned to a nutrient group.
      nutrient_group_name:
        type: string
        description: The name of the nutrient group.
      nutrient_group_order:
        type: string
        description: The order to display the nutrient group.
    xml:
      name: NutrientGroup

  NutrientSource:
    type: object
    description: It contains a list of several sources and/or types of nutrient data.
    properties:
      nutrient_source_id:
        type: string
        description: The identification number assigned to a nutrient source.
      nutrient_source_description:
        type: string
        description: The description of the nutrient source.
      nutrient_source_code:
        type: string
        description: The code that identifies a nutrient source in Canada.
    xml:
      name: NutrientSource

  NutrientAmount:
    type: object
    description: Identify the nutrient amount per 100 grams for a food.
    properties:
      food_code:
        type: string
        description: The code assigned to each food.
      nutrient_value:
        type: string
        description: The mean value in 100g, edible portion. (The number of decimal places does not reflect the accuracy of the data).
      standard_error:
        type: string
        description: The standard error of the mean.
      number_observation:
        type: string
        description: The number of samples observed for the study.
      nutrient_name_id:
        type: string
        description: The identification number of the nutrient.
      nutrient_web_name:
        type: string
        description: The name of the nutrient for the WEB.
      nutrient_source_id:
        type: string
        description: The identification number of the nutrient source.
    xml:
      name: NutrientAmount

  ServingSize:
    type: object
    description: Measures and conversion factors per food. The conversion factors are food specific multipliers by which the nutrient values for each food may be multiplied to give the nutrients in described portions.
    properties:
      food_code:
        type: string
        description: The code assigned to each food.
      food_description:
        type: string
        description: The complete food name.
      conversion_factor_value:
        type: string
        description: The factor by which one would multiply the nutrient per 100g to obtain nutrient amounts per the measure described.
      measure_name:
        type: string
        description: The measure description.
    xml:
      name: ServingSize

  RefuseAmount:
    type: object
    description: Refuse amount is the percent of refuse, or inedible portion, for each food.
    properties:
      food_code:
        type: string
        description: The code assigned to each food.
      food_description:
        type: string
        description: The complete food name.
      refuse_amount:
        type: string
        description: The percent refuse.
      refuse_name:
        type: string
        description: The refuse description.
    xml:
      name: RefuseAmount

  YieldAmount:
    type: object
    description: Contains the yield from refuse and/or cooking losses assigned to certain foods. These yields are most often used for food inventory purposes.
    properties:
      food_code:
        type: string
        description: The code assigned to each food.
      food_description:
        type: string
        description: The complete food name.
      yield_amount:
        type: string
        description: The yield from refuse and/or cooking losses.
      yield_name:
        type: string
        description: The yield description.
    xml:
      name: YieldAmount

parameters:
  QueryLang:
    name: lang
    type: string
    in: query
    enum:
      - en
      - fr
    default: en
    description: Define which language you would like the response to be in
  QueryType:
    name: type
    type: string
    in: query
    enum:
      - json
      - xml
    default: json
    description: Define which media type you would like the content to be in
  PathID:
    name: id
    description: The drug product code identifier
    in: path
    type: string
    required: true
  UserKeys:
    name: 'user_key'
    type: string
    in: query
    required: true
    description: The identifier assigned to your account for accessing the API
    x-data-threescale-name: user_key
